TC 06.2.1_02 Select the men's bottom section
RedRoverSchool/LumaProjectJS_2024_spring pull request #253
Opened 2024-04-22 18:02 UTC by LenaDik

https://trello.com/c/ukgQQb1g/458-us-0622-men-bottom

2024-04-22 20:13 UTC, alenavolakhava requested changes
test fails due to an undeclared BaseURL variable, please get it fixed and i will take a look again

2024-04-22 20:13 UTC, alenavolakhava commented on tests/menBottoms.spec.js
> +    await expect(page).toHaveURL(BASE_URL + '/men/bottoms-men.html');
Playwright error: `ReferenceError: BASE_URL is not defined` and it fails. you need to define the variable before using it. something like this: `const BASE_URL = "https://example.com"`

2024-04-22 21:00 UTC, alfiyaGumar approved these changes

2024-04-22 22:29 UTC, verafes commented on tests/menBottoms.spec.js
> +    await expect(page).toHaveURL(BASE_URL + '/men/bottoms-men.html');
it has beforeEach with directions to the base URL: await page.goto('/'); So we do not need to put navigation in each test.

2024-04-22 23:24 UTC, LenaDik commented on tests/menBottoms.spec.js
> +    await expect(page).toHaveURL(BASE_URL + '/men/bottoms-men.html');
but in other test cases we use BASE_URL, maybe everything should be in the same style and I will use BASE_URL in my TC?

2024-04-22 23:27 UTC, alfiyaGumar approved these changes

2024-04-22 23:34 UTC, alenavolakhava approved these changes
the test passed
<img width="1517" alt="Screenshot 2024-04-22 at 7 32 57 PM" src="https://github.com/RedRoverSchool/LumaProjectJS_2024_spring/assets/51464730/c5e8ac1a-eaf8-4903-8259-c07e85d17fc1">

2024-04-22 23:45 UTC, merged

2024-04-23 04:39 UTC, skatoy reviewed
+