TC 06.1.4_01 Checking that the grid is selected and has 12 positions by default
RedRoverSchool/LumaProjectJS_2024_spring pull request #91
Opened 2024-04-16 17:59 UTC by trukhachev495

[Trello C 06.1.4_01](https://trello.com/c/brGJWiW8/266-tc-061401-checking-that-the-grid-is-selected-and-has-12-positions-by-defaulturl)

2024-04-16 18:19 UTC, S-Lanchik commented on tests/menTopsDisplayMode.spec.js
> +    await page.goto('https://magento.softwaretestingboard.com/')
You don't need this line, line 5 does the same action.

2024-04-16 18:20 UTC, S-Lanchik commented on tests/menTopsDisplayMode.spec.js
> +    await page.goto('https://magento.softwaretestingboard.com/')
Add PR link to Trello

2024-04-16 18:35 UTC, annanazcz requested changes

2024-04-16 18:35 UTC, annanazcz commented on tests/menTopsDisplayMode.spec.js
> +    await page.goto('https://magento.softwaretestingboard.com/')
ты этот же степ уже делаешь на 4й строке ;)

2024-04-16 18:39 UTC, trukhachev495 commented on tests/menTopsDisplayMode.spec.js
> +    await page.goto('https://magento.softwaretestingboard.com/')
забыл удалить, делал в другом файле, спасибо)

2024-04-16 18:44 UTC, trukhachev495 commented on tests/menTopsDisplayMode.spec.js
> +    await page.goto('https://magento.softwaretestingboard.com/')
ok

2024-04-16 20:57 UTC, verafes approved these changes

2024-04-17 03:39 UTC, Sensation3000 approved these changes

2024-04-17 03:45 UTC, Sensation3000 commented on tests/menTopsDisplayMode.spec.js
> +    await page.goto('https://magento.softwaretestingboard.com/')
@annanazcz please do not request changes for minor mistakes. Just write in the comments section about this without "requesting". Cause @trukhachev495 after that is waiting only your approval. The mistake has been corrected 6 hours  ago and PRs still waits for you to approve

2024-04-17 03:49 UTC, Sensation3000 commented on tests/menTopsDisplayMode.spec.js
> +    await page.goto('/')
the 5 and 8 line are doing the same thing

2024-04-17 08:33 UTC, closed without merging